:USER_GUID: %GUID%
:USERNAME: %user%
:CLUSTER: %cluster%


== Test Change OpenShift Application Migration Lab

=== Migrating from OCP/OCS 3 to OCP/OCS 4

This guide will provide you with hands-on exposure to the OpenShift Migration +
Tooling through a series of exercises migrating application workloads (both +
stateful and stateless) between OpenShift Clusters.

=== Goals

In this instructor-led, hands-on lab, you’ll experience:

* Migrating applications from Red Hat OpenShift 3 clusters to Red Hat OpenShift +
4 clusters using the Cluster Application Migration Tool (CAM) provided by OpenShift +
Container Platform 4.3.

* Use cases that migrate applications preserving state, including how to migrate +
OpenShift Container Storage 3 (Gluster) to OpenShift Container Storage 4 (Ceph).

=== Modules

link:/workshop/Intro[Module 1 - Introduction] +
link:/workshop/Environment[Module 2 - Environment] +
link:/workshop/Prereqs[Module 3 - Prerequisites] +
link:/workshop/Overview[Module 4 - CAM Overview] +
link:/workshop/exercises/Ex1[Module 5 - Migration Exercise (Migrate File-Uploader Application)] +
link:/workshop/exercises/Ex2[Module 6 - Migration Exercise (Migrate MSSQL Server Application)] +
link:/workshop/exercises/Ex3[Module 7 - Migration Exercise (Migrate Sock-Shop Application)] +
link:/workshop/exercises/Ex4[Module 8 - Migration Exercise (Migration at Scale via API)] +
link:/workshop/Debug[Module 9 - Debugging Failed Migrations] +
link:/workshop/Conclusion[Module 10 - Conclusion]
